urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "MyMovie"
urlpatterns = [
    path("", Movie_Home, name = "home"),
    path("login_account", Login_Account, name = "login_account"),
    path("logout_account", Logout, name = "logout_account"),
    path("create_account/", Register, name = "register"),
    path("movie_booking_page/<int:st_id>/", SheetBookingPage, name = "sheet_booking"),
    #path("create_sheets/", Create_Sheets, name = "sheets"),
    path("contact", Movie_Contact, name = "contact"),
    path("payMentMake", MakePayment, name = "payment"),
    path("add_show_time", Admin_Add_ShowTime, name = "add_show_time"),
    path("all_movies", All_Movies, name = "all_movies"),
    path("add_movie_category", Admin_Add_Cat, name = "add_cat"),
    path("movie_details/<int:m_id>/", Movie_Details_Page, name = "movie_detail"),
    path("booking/<int:m_id>/", Movie_Confirmation, name = "confirmation"),
    path("PayCheck/<str:Usr>/", PayChack, name = "paycheck"),


    ]

templates/movie/add_cat.html
{% extends 'movie/base.html' %}

{% load static %}
{% block body %}
    <center>
        <h2 style="padding-top: 15%">Add Category</h2>
        <br>
        <form style="width: 40%;" method="post" action="">
            {% csrf_token %}
            {% if error %}<p style="color: red">This Category Already Exist</p>{% endif %}
            <label>Category Name:</label>
            <input type="text" name="cat" placeholder="Category" class="form-control" required><br>
            <input class="btn btn-info" type="submit" value="Add" >

        </form>
        <br>
        <br>
        <span style="color: #9e1847">New User: Create Account. <a href="{% url 'MyMovie:register' %}">Click..></a></span>

    </center>
{% endblock %}

templates/movie/add_st.html
{% extends 'movie/base.html' %}

{% load static %}
{% block body %}
    <center>
        <h2 style="padding-top: 15%">Add New Show Time</h2>
        <br>
        <form style="width: 40%;" method="post" action="">
            {% csrf_token %}


            <select name="talkies" required class="form-control">
                <option value="">-----------Choose Talkies----------</option>
                {% for i in talk %}
                    <option value="{{ i.id }}">{{ i.name }}</option>
                {% endfor %}
            </select><br><br><br>

            <select name="movie" required class="form-control">
                <option value="">-----------Choose Movie----------</option>
                {% for i in movies %}
                    <option value="{{ i.id }}">{{ i.title }}</option>
                {% endfor %}
            </select><br><br><br>
            <input type="date" class="form-control" name="date" placeholder="Show Date" required><br><br>
            <input type="text" class="form-control" name="time" placeholder="Show Time" required><br><br>
            <input type="number" class="form-control" name="rs" placeholder="Fee" required><br><br>
            <br><br>



            <input class="btn btn-info" type="submit" value="Add" >

        </form>
        <br>
        <br>
        <span style="color: #9e1847">New User: Create Account. <a href="{% url 'MyMovie:register' %}">Click..></a></span>

    </center>
{% endblock %}

templates/movie/contact.html


{% extends 'movie/base.html' %}

{% load static %}
{% block body %}


	<!-- prs title wrapper Start -->
	<div class="prs_title_main_sec_wrapper">
		<div class="prs_title_img_overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="prs_title_heading_wrapper">
						<h2>contact us</h2>
						<ul>
							<li><a href="contact.html#">Home</a>
							</li>
							<li>&nbsp;&nbsp; >&nbsp;&nbsp; contact</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- prs title wrapper End -->
	<!-- prs contact form wrapper Start -->
	<div class="prs_contact_form_main_wrapper">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
					<div class="prs_contact_left_wrapper">
						<h2>Contact us</h2>
					</div>
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
							<div class="prs_contact_input_wrapper">
								<input type="text" placeholder="Name">
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
							<div class="prs_contact_input_wrapper">
								<input type="email" placeholder="Email">
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="prs_contact_input_wrapper">
								<textarea rows="7" placeholder="Comment"></textarea>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="prs_contact_input_wrapper prs_contact_input_wrapper2">
								<ul>
									<li><a href="contact.html#">Submit</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
					<div class="prs_contact_right_section_wrapper">
						<ul>
							<li><a href="contact.html#"><i class="fa fa-facebook"></i> &nbsp;&nbsp;&nbsp;facebook.com/presenter</a>
							</li>
							<li><a href="contact.html#"><i class="fa fa-twitter"></i> &nbsp;&nbsp;&nbsp;twitter.com/presenter</a>
							</li>
							<li><a href="contact.html#"><i class="fa fa-vimeo"></i> &nbsp;&nbsp;&nbsp;vimeo.com/presenter</a>
							</li>
							<li><a href="contact.html#"><i class="fa fa-instagram"></i> &nbsp;&nbsp;&nbsp;instagram.com/presenter</a>
							</li>
							<li><a href="contact.html#"><i class="fa fa-youtube-play"></i> &nbsp;&nbsp;&nbsp;youtube.com/presenter</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- prs contact form wrapper End -->
	<!-- prs contact map Start -->
	<div class="hs_contact_map_main_wrapper">
		<div id="map"></div>
	</div>
	<!-- prs contact map End -->
	<!-- prs contact info Start -->
	<div class="prs_contact_info_main_wrapper">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					<div class="prs_contact_info_box_wrapper">
						<div class="prs_contact_info_smallbox">	<i class="flaticon-call-answer"></i>
						</div>
						<h3>contact</h3>
						<p>+91-123456789
							<br>+91-4444-5555</p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					<div class="prs_contact_info_box_wrapper prs_contact_info_box_wrapper2">
						<div class="prs_contact_info_smallbox">	<i class="flaticon-call-answer"></i>
						</div>
						<h3>Location</h3>
						<p>601 - Ram Nagar , India
							<br>Omex City 245 , America</p>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					<div class="prs_contact_info_box_wrapper prs_contact_info_box_wrapper2">
						<div class="prs_contact_info_smallbox">	<i class="flaticon-call-answer"></i>
						</div>
						<h3>Email</h3>
						<p><a href="contact.html#">presenter@example.com</a> 
							<br> <a href="contact.html#">movie@example.com</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- prs contact info End -->

    {% endblock %}

templates/movie/login.html
{% extends 'movie/base.html' %}

{% load static %}
{% block body %}
    <center>
        <h2 style="padding-top: 15%">Login Your Account</h2>
        <br>
        <form style="width: 40%;" method="post" action="">
            {% csrf_token %}
            {% if error %}<p style="color: red">Wrong Username or Password</p>{% endif %}
            <label>Username:</label>
            <input type="text" name="un" placeholder="Username" class="form-control" required><br>
            <label>Password:</label>
            <input type="password" name="ps" placeholder="Password" class="form-control" required><br>
            <input class="btn btn-info" type="submit" value="Login" >

        </form>
        <br>
        <br>
        <span style="color: #9e1847">New User: Create Account. <a href="{% url 'MyMovie:register' %}">Click..></a></span>

    </center>
{% endblock %}

templates/movie/movie_booking.html

{% extends 'movie/base.html' %}

{% load static %}
{% block body %}


	<!-- prs title wrapper Start -->
	<div class="prs_title_main_sec_wrapper">
		<div class="prs_title_img_overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="prs_title_heading_wrapper">
						<h2>Movie Booking</h2>
						<ul>
							<li><a href="movie_booking.html#">Home</a>
							</li>
							<li>&nbsp;&nbsp; >&nbsp;&nbsp; Movie Bookin</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- prs title wrapper End -->
	<!-- prs video top Start -->
	<div class="prs_booking_main_div_section_wrapper">
	<div class="prs_top_video_section_wrapper">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="st_video_slider_inner_wrapper float_left">
						<div class="st_video_slider_overlay"></div>
						<div class="st_video_slide_sec float_left">
							<a rel='external' href='https://www.youtube.com/embed/ryzOXAO0Ss0' title='title' class="test-popup-link">
								<img src="{% static 'images/index_III/icon.png' %}" alt="img">
							</a>
							<h3>Aquaman</h3>
							<p>ENGLISH, HINDI, TAMIL</p>
							<h4>ACTION | Adventure | Fantasy</h4>
							<h5><span>2d</span> <span>3d</span> <span>D 4DX</span> <span>Imax 3D</span></h5>
						</div>
						<div class="st_video_slide_social float_left">
						<div class="st_slider_rating_btn_heart st_slider_rating_btn_heart_5th">
								<h5><i class="fa fa-heart"></i> 85%</h5>
								<h4>52,291 votes</h4>
							</div>
							<div class="st_video_slide_social_left float_left">
								<ul>
									<li><a href="movie_booking.html#"><i class="fa fa-facebook-f"></i></a>
									</li>
									<li><a href="movie_booking.html#"><i class="fa fa-twitter"></i></a>
									</li>
									<li><a href="movie_booking.html#"><i class="fa fa-linkedin"></i></a>
									</li>
									<li><a href="movie_booking.html#"><i class="fa fa-youtube"></i></a>
									</li>
								</ul>
							</div>
							<div class="st_video_slide_social_right float_left">
								<ul>
									<li data-animation="animated fadeInUp" class=""><i class="far fa-calendar-alt"></i> 14 Dec, 2018</li>
									<li data-animation="animated fadeInUp" class=""><i class="far fa-clock"></i> 2 hrs 23 mins</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- prs video top End -->
	<!-- st slider rating wrapper Start -->
	<div class="st_slider_rating_main_wrapper float_left">
		<div class="container">
			<div class="st_calender_tabs">
				<ul class="nav nav-tabs">
                    {% for d, st in data %}
                        {% if forloop.counter == 3 %}
                            <li class="active">
                        {% else %}
                                <li>
                            {% endif %}
                            <a data-toggle="tab" href="#movie{{ forloop.counter }}"><span>{{ d }}</span></a>
					</li>{% endfor %}

				</ul>
			</div>
		</div>
	</div>
	<!-- st slider rating wrapper End -->
	<!-- st slider sidebar wrapper Start -->
	<div class="st_slider_index_sidebar_main_wrapper st_slider_index_sidebar_main_wrapper_booking float_left">
		<div class="container">
			<div class="row">
				<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
					<div class="st_indx_slider_main_container float_left">
						<div class="row">
							<div class="col-md-12">
								<div class="tab-content">
                                    {% for d, st in data2 %}
									    {% if forloop.counter == 1 %}
                                            <div id="movie{{ forloop.counter }}" class="tab-pane active">
									    {% else %}<div id="movie{{ forloop.counter }}" class="tab-pane ">
										{% endif %}
                                            <div class="st_calender_contant_main_wrapper float_left">
											{% for t, ss in st %}
                                                <div class="st_calender_row_cont float_left">
												<div class="st_calender_asc">
													<div class="st_calen_asc_heart"><a href="movie_booking.html#">	<i class="fa fa-heart"></i></a>
													</div>
													<div class="st_calen_asc_heart_cont">
														<h3>{{ t }}</h3>
														<ul>
															<li>
																<img src="{% static 'images/content/fast-food.png' %}">
															</li>
															<li>
																<img src="{% static 'images/content/bill.png' %}">
															</li>
														</ul>
													</div>
												</div>
												<div class="st_calen_asc_tecket_time_select">
													<ul>
                                                        {% for s in ss %}
														<li>	<span>
															<h4>Rs.{{ s.Rs }}</h4>
															<p class="asc_pera1">Executive</p>
															<p class="asc_pera2">Filling Fast</p>
															</span>
															<a href="{% url 'MyMovie:sheet_booking' s.id %}">{{ s.time }}</a>
														</li>{% endfor %}

													</ul>
												</div>
											</div>
                                                {% endfor %}
										</div>
									</div>
                                    {% endfor %}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
					<div class="prs_mcc_left_side_wrapper">
						<div class="prs_mcc_left_searchbar_wrapper">
							<input type="text" placeholder="Search Movie">
							<button><i class="flaticon-tool"></i>
							</button>
						</div>
						<div class="prs_mcc_bro_title_wrapper">
							<h2>browse title</h2>
							<ul>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">All <span>23,124</span></a> 
								</li>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">Action <span>512</span></a> 
								</li>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">Romantic <span>548</span></a> 
								</li>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">Love <span>557</span></a> 
								</li>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">Musical <span>554</span></a> 
								</li>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">Drama <span>567</span></a> 
								</li>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">Thriller <span>689</span></a> 
								</li>
								<li><i class="fa fa-caret-right"></i> &nbsp;&nbsp;&nbsp;<a href="movie_booking.html#">Horror <span>478</span></a> 
								</li>
							</ul>
						</div>
						<div class="prs_mcc_event_title_wrapper">
							<h2>Top Events</h2>
							<img src="{% static 'images/content/movie_category/event_img.jpg' %}" alt="event_img">
							<h3><a href="movie_booking.html#">Music Event in india</a></h3>
							<p>Pune <span><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></span>
							</p>
							<h4>June 07 <span>08:00-12:00 pm</span></h4>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>



{% endblock %}

templates/movie/register.html
{% extends 'movie/base.html' %}

{% load static %}
{% block body %}
    <center>
        <h2 style="padding-top: 15%">Create New Account</h2>
        <br>
        <form style="width: 40%;" method="post" action="">
            {% csrf_token %}
            {% if error %}<p style="color: red">Thsi Username already Exist.</p>{% endif %}
            <label>Username:</label>
            <input type="text" name="un" placeholder="Username" class="form-control" required><br>
            <label>Password:</label>
            <input type="password" name="ps" placeholder="Password" class="form-control" required><br>
            <label>Email:</label>
            <input type="email" name="email" placeholder="Email" class="form-control" required><br>
            <label>Name:</label>
            <input type="text" name="name" placeholder="Name" class="form-control" required><br>
            <label>Number:</label>
            <input type="number" name="number" placeholder="Mobile Number" class="form-control" required><br>
            <label>Address:</label>
            <textarea  name="add" placeholder=" Your Complete Address" class="form-control" required></textarea><br>

            <input class="btn btn-info" type="submit" value="Register" >

        </form>


    </center>
{% endblock %}